<a href="https://colab.research.google.com/github/singlaamitesh/communityclassroom-/blob/master/Movie_Recommend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Topic is Movie Recommendation
System

The objective of a movie recommendation system is to predict user preferences for movies and suggest movies that they are likely to enjoy.

This is done by analyzing past user behavior, such as ratings or viewing history, and identifying patterns to recommend relevant movies.

So our motive is to tell what movie are most similar to the user's movie choice

In [1]:
import pandas as pd

In [4]:
mov = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv")

In [5]:
mov.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [6]:
mov.describe()

,Movie_ID,Movie_Budget,Movie_Popularity,Movie_Revenue,Movie_Runtime,Movie_Vote,Movie_Vote_Count
count,4760.000000,4.760000e+03,4760.000000,4.760000e+03,4758.000000,4760.000000,4760.000000
mean,2382.566387,2.920129e+07,21.599510,8.263743e+07,107.184111,6.113866,692.508403
std,1377.270159,4.075620e+07,31.887919,1.630554e+08,21.960332,1.141294,1235.007337
min,1.000000,0.000000e+00,0.000372,0.000000e+00,0.000000,0.000000,0.000000
25%,1190.750000,9.257500e+05,4.807074,0.000000e+00,94.000000,5.600000,55.000000
50%,2380.500000,1.500000e+07,13.119058,1.944716e+07,104.000000,6.200000,238.000000
75%,3572.250000,4.000000e+07,28.411929,9.341276e+07,118.000000,6.800000,740.250000
max,4788.000000,3.800000e+08,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Movie_ID                  4760 non-null   int64
 1   Movie_Title               4760 non-null   object
 2   Movie_Genre               4760 non-null   object
 3   Movie_Language            4760 non-null   object
 4   Movie_Budget              4760 non-null   int64
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object
 7   Movie_Revenue             4760 non-null   int64
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64
 11  Movie_Homepage            1699 non-null   object
 12  Movie_Keywords            4373 non-null   object
 13  Movie_Overview            4757 non-null   object
 14  Movie_Production_House    4760 non-null   object
 15  Movie_Production_Country  4760 non-null   object
 16  Movie_Spoken_Language     4760 non-null   object
 17  Movie_Tagline             3942 non-null   object
 18  Movie_Cast                4733 non-null   object
 19  Movie_Crew                4760 non-null   object
 20  Movie_Director            4738 non-null   object
dtypes: float64(3), int64(4), object(14)
memory usage: 781.1+ KB

In [9]:
mov.shape

(4760, 21)

In [10]:
mov.isna().sum()

Movie_ID                       0
Movie_Title                    0
Movie_Genre                    0
Movie_Language                 0
Movie_Budget                   0
Movie_Popularity               0
Movie_Release_Date             0
Movie_Revenue                  0
Movie_Runtime                  2
Movie_Vote                     0
Movie_Vote_Count               0
Movie_Homepage              3061
Movie_Keywords               387
Movie_Overview                 3
Movie_Production_House         0
Movie_Production_Country       0
Movie_Spoken_Language          0
Movie_Tagline                818
Movie_Cast                    27
Movie_Crew                     0
Movie_Director                22
dtype: int64

In [11]:
import numpy as np

In [12]:
mov.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director'],
      dtype='object')

In [24]:
mov_features = mov[['Movie_ID',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime']].fillna('')

In [25]:
mov_features.shape
mov_features

,Movie_ID,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime
0,1,4000000,22.876230,09-12-1995,4300000,98.0
1,2,11000000,126.393695,25-05-1977,775398007,121.0
2,3,94000000,85.688789,30-05-2003,940335536,100.0
3,4,55000000,138.133331,06-07-1994,677945399,142.0
4,5,15000000,80.878605,15-09-1999,356296601,122.0
...,...,...,...,...,...,...
4755,4784,0,0.001389,01-01-1990,0,94.0
4756,4785,0,0.710870,03-02-2017,0,102.0
4757,4786,0,0.015295,15-06-2014,0,90.0
4758,4787,0,0.028756,27-10-2015,0,88.0
4759,4788,2,0.050625,12-12-2015,0,

In [28]:
# Convert numerical columns to strings
mov_features['Movie_Budget'] = mov_features['Movie_Budget'].astype(str)
mov_features['Movie_Popularity'] = mov_features['Movie_Popularity'].astype(str)
mov_features['Movie_Revenue'] = mov_features['Movie_Revenue'].astype(str)
mov_features['Movie_Runtime'] = mov_features['Movie_Runtime'].astype(str)

# Combine the features
x = mov_features['Movie_Budget']+ ' ' + mov_features['Movie_Popularity']+ ' '+ mov_features['Movie_Release_Date']+ ' ' +mov_features['Movie_Revenue']+ ' '+mov_features['Movie_Runtime']

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
hi = TfidfVectorizer()

In [32]:
x = hi.fit_transform(x)

In [33]:
x.shape

(4760, 8627)

In [34]:
print(x)

  (0, 8515)	0.2814470113612795
  (0, 4689)	0.52202961678126
  (0, 2298)	0.32468006023938184
  (0, 973)	0.18062527976332832
  (0, 501)	0.18036412611500863
  (0, 7839)	0.5473193291667947
  (0, 2592)	0.2476824230906493
  (0, 4430)	0.34175104537588336
  (1, 999)	0.30003620246718127
  (1, 7156)	0.491444979747054
  (1, 2256)	0.37159120395601447
  (1, 278)	0.18357769078271166
  (1, 2932)	0.21862515554075795
  (1, 4381)	0.491444979747054
  (1, 1093)	0.3280360884249443
  (1, 784)	0.3158425487754246
  (2, 554)	0.25272651747335556
  (2, 8283)	0.501926808199071
  (2, 2320)	0.24882908903997897
  (2, 3433)	0.24781067862711154
  (2, 6562)	0.501926808199071
  (2, 7665)	0.29775236801872845
  (2, 8280)	0.43026975963824937
  (2, 278)	0.18749314407189208
  (3, 1368)	0.39519117085579547
  :	:
  (4754, 3235)	0.2685122079121402
  (4754, 2308)	0.24055906492818968
  (4754, 553)	0.17295696793256768
  (4755, 11)	0.665062026843796
  (4755, 2284)	0.45981896762220725
  (4755, 8278)	0.3534989961386797
  (4755, 68)	0.47042265803659516
  (4756, 2349)	0.6212057845175457
  (4756, 6731)	0.6212057845175457
  (4756, 607)	0.34286339091492507
  (4756, 114)	0.23889825350390811
  (4756, 172)	0.2314715235336367
  (4757, 89)	0.7470492632698569
  (4757, 8003)	0.37189123808862473
  (4757, 2338)	0.34199484662736623
  (4757, 1496)	0.33498404108487145
  (4757, 329)	0.2728360723578302
  (4758, 161)	0.731213276432512
  (4758, 2340)	0.3434056334492563
  (4758, 7867)	0.41038616270210065
  (4758, 3143)	0.34915470754119515
  (4758, 553)	0.23890145028570556
  (4759, 282)	0.7770386056170119
  (4759, 2340)	0.36492695520834817
  (4759, 973)	0.5128735933377095

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
sim = cosine_similarity(x)

In [37]:
sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.09263794],
       [0.        , 1.        , 0.03441956, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.03441956, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.12531797],
       [0.09263794, 0.        , 0.        , ..., 0.        , 0.12531797,
        1.        ]])

In [38]:
Favourite_Movie_Name = input('Enter your favourite movie name : ')

Enter your favourite movie name : Star Wars

In [39]:
All_movie = mov['Movie_Title'].tolist()

In [40]:
import difflib

In [41]:
movierec = difflib.get_close_matches(Favourite_Movie_Name, All_movie)

In [42]:
print(movierec)

['Star Wars', 'Star Trek', 'State Fair']

In [43]:
close = movierec[0]

In [44]:
sorted_movie = sorted(list(enumerate(sim[0])), reverse = True, key = lambda x:x[1])

In [45]:
print("top 20 movie name")

top 20 movie name

In [46]:
i = 1
for movie in sorted_movie:
  index = movie[0]
  title_from_index = mov[mov.index==index]['Movie_Title'].values[0]
  if(i<20):
    print(i, '.',title_from_index)
    i = i+1
  else:
    break

1 . Four Rooms
2 . Class of 1984
3 . Bang
4 . The Brothers McMullen
5 . The Prophecy
6 . Samsara
7 . Tales from the Hood
8 . Showgirls
9 . Tank Girl
10 . Cutthroat Island
11 . Nixon
12 . Richard III
13 . Three to Tango
14 . Se7en
15 . Elite Squad
16 . Joe
17 . The Veil
18 . The Front Page
19 . Flightplan